# Generated by Django 5.1.7 on 2025-03-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='session_string',
            field=models.TextField(blank=True, null=True),
        ),
    ]
